channels:
  - r 
  - bioconda
  - conda-forge 
dependencies:
  - r-tidyverse
  - bioconductor-ggtree
  - bioconductor-ggtreeextra
  - bioconductor-phyloseq
  - bioconductor-treeio
  - bioconductor-biostrings
  - fasttree
  - r-tidytree
  - r-treemap
  - r-treemapify
  - r-ggstance
